### ISSUE TITLE
.tw后缀域名无法查询

### ISSUE THREAD

**Issue by ashq3** [dromara/domain-admin#159]
![image](https://github.com/user-attachments/assets/f672545e-964c-4081-8c2e-4e8b4f5aade3)

**Comment by mouday** [comment]
v1.6.62 已修复

**Comment by mouday** [comment]
<img width="786" alt="image" src="https://github.com/user-attachments/assets/04d4b9de-6058-49bc-a78d-8d43a6c532bb" />
