### ISSUE TITLE
企业微信通知提示isJson is not defined

### ISSUE THREAD

**Issue by iStarCc** [dromara/domain-admin#98]
企业微信通知提示isJson is not defined

**Comment by mouday** [comment]
参数不对？

**Comment by iStarCc** [comment]
> 参数不对？
感觉都是正确的？
<img width="813" alt="iShot_2024-04-09_14 02 46" src="https://github.com/mouday/domain-admin/assets/148518645/33bb89d1-9f92-43be-8735-5ba96944756d">

**Comment by mouday** [comment]
我知道了，这个改出问题了，一会修复下

**Comment by seclionys** [comment]
> 我知道了，这个改出问题了，一会修复下

飞书的通知也有这个问题

**Comment by mouday** [comment]
> > 我知道了，这个改出问题了，一会修复下
> 
> 飞书的通知也有这个问题

新版本已经修复了，你用的什么版本

**Comment by seclionys** [comment]
> > > 我知道了，这个改出问题了，一会修复下
> > 
> > 
> > 飞书的通知也有这个问题
> 
> 新版本已经修复了，你用的什么版本

1.6.28最新版

**Comment by mouday** [comment]
不应该呀，已经修复了，我试了下没有这个报错了
<img width="146" alt="image" src="https://github.com/mouday/domain-admin/assets/24365682/7b57d47b-4cb2-4765-a05c-7d91222ede3d">

**Comment by seclionys** [comment]
> 不应该呀，已经修复了，我试了下没有这个报错了 <img alt="image" width="146" src="https://private-user-images.githubusercontent.com/24365682/324340436-7b57d47b-4cb2-4765-a05c-7d91222ede3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NjQ4MzMsIm5iZiI6MTcxMzc2NDUzMywicGF0aCI6Ii8yNDM2NTY4Mi8zMjQzNDA0MzYtN2I1N2Q0N2ItNGNiMi00NzY1LWEwNWMtN2Q5MTIyMmVkZTNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDA1NDIxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmNzJhOTEyN2Q2N2UwYzA5ZWUxZmY2NzZmOTk4NDRkNDE3MDVkN2M5YmJmZTYzOTY4YTMzOWE1YTAwMDYwYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ryqsRpWOTPDxPWjy4VlkwYRW6bayx-OQKh7HEj9Y3Jc">

![20240422-134640](https://github.com/mouday/domain-admin/assets/136969236/0aa38b42-d5e5-4d8a-9209-6fd1946cb9a1)

**Comment by seclionys** [comment]
确实是版本问题，已经升级了

**Comment by mouday** [comment]
左下角，pypi的版本是1.6.28是最新版，你的版本是1.6.25，升级下就好了

**Comment by iStarCc** [comment]
> 左下角，pypi的版本是1.6.28是最新版，你的版本是1.6.25，升级下就好了

企业微信恶意保存了，但是测试发送，无法收到消息，同样的应用参数在其他项目可以收到

**Comment by Eric-3A** [comment]
> > 左下角，pypi的版本是1.6.28是最新版，你的版本是1.6.25，升级下就好了
> 
> 企业微信可以保存了，但是测试发送，无法收到消息，同样的应用参数在其他项目可以收到

企业微信确实收不到。。。。

**Comment by mouday** [comment]
尝试增加【报警天数】

https://domain-admin.readthedocs.io/zh-cn/latest/manual/notify.html

<img width="1083" alt="image" src="https://github.com/user-attachments/assets/518c37df-128d-42fe-802d-801108e8c003">

**Comment by Eric-3A** [comment]
看到了这个提示，已增加了与当前证书剩余天数一样的值，也更改了定时任务，手动触发了检测，没有发现有行告警

**Comment by mouday** [comment]
再改大一点试试，企业微信配置正确就能收到

**Comment by mouday** [comment]
再改大一点试试，企业微信配置正确就能收到

**Comment by Eric-3A** [comment]
> 再改大一点试试，企业微信配置正确就能收到

监测设置，是根据运行服务的那个机器时间吧

**Comment by Eric-3A** [comment]
可以了
